- name: Run tests
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Send coverage to Coveralls
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverage.txt

    - name: Run gosec