
name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        
    - name: Verify dependencies
      run: go mod verify
        
    - name: Install golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        
    - name: Run golangci-lint
      run: golangci-lint run --timeout=5m
        
    - name: Run tests
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      
    - name: Send coverage to Coveralls
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverage.txt

    - name: Run gosec
      uses: securego/gosec@master
      with:
        args: ./...
